### ISSUE TITLE
feat: dynamicAlbumArt - would automatically upload and set album art in rich presence

### ISSUE THREAD

**Issue by sammy-ette** [sammy-ette/clematis#4]

**Comment by TorchedSammy** [comment]
https://github.com/TorchedSammy/Clematis/commit/102becd322ce09040a30ef220a6aad9f55ba41a1
i was experimenting with it but realized it was kinda broken a bit and i have no idea why,
and it wouldn't instantly apply the image since discord cache.
i branched it out separately so if anyone wants to work on it they can
so i won't really bother to do this anymore
